# docker-compose.yml
version: '3.1'
services:
    db:
        build: 
            context: .
            dockerfile: Dockerfile.dockerfile
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432

   
            